// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcl-V9QP-hg61H_0BpX2IpspjQnB4sitw',
    appId: '1:511571892610:web:c6c24437ea8737b324579b',
    messagingSenderId: '511571892610',
    projectId: 'smart-wallet-6f35e',
    authDomain: 'smart-wallet-6f35e.firebaseapp.com',
    storageBucket: 'smart-wallet-6f35e.firebasestorage.app',
    measurementId: 'G-B4VL2TDBCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkP5t7f22YfMuiBQoVshNau9WTEE_kod4',
    appId: '1:511571892610:android:bb9dba7338b890ad24579b',
    messagingSenderId: '511571892610',
    projectId: 'smart-wallet-6f35e',
    storageBucket: 'smart-wallet-6f35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJrVLlrlbIsQrBFr_qzBy_BzKzgKLseM',
    appId: '1:511571892610:ios:4c271036e5e32f5224579b',
    messagingSenderId: '511571892610',
    projectId: 'smart-wallet-6f35e',
    storageBucket: 'smart-wallet-6f35e.firebasestorage.app',
    iosBundleId: 'com.antigravity.smartWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJrVLlrlbIsQrBFr_qzBy_BzKzgKLseM',
    appId: '1:511571892610:ios:4c271036e5e32f5224579b',
    messagingSenderId: '511571892610',
    projectId: 'smart-wallet-6f35e',
    storageBucket: 'smart-wallet-6f35e.firebasestorage.app',
    iosBundleId: 'com.antigravity.smartWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcl-V9QP-hg61H_0BpX2IpspjQnB4sitw',
    appId: '1:511571892610:web:3410e3e7c277a01124579b',
    messagingSenderId: '511571892610',
    projectId: 'smart-wallet-6f35e',
    authDomain: 'smart-wallet-6f35e.firebaseapp.com',
    storageBucket: 'smart-wallet-6f35e.firebasestorage.app',
    measurementId: 'G-GL2BKYE7G7',
  );
}
