import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'core/theme.dart';
import 'core/router.dart';
import 'core/currency_service.dart';
import 'core/theme_provider.dart';
import 'features/expenses/models/expense_model.dart';
import 'features/settings/models/budget_model.dart';
import 'features/auth/screens/login_screen.dart';

// ⚠️  firebase_options.dart is generated by the FlutterFire CLI.
// Run: flutterfire configure
// Then uncomment the line below:
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase init ────────────────────────────────────────────────────────
  // After running `flutterfire configure`, replace the line below with:
  //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp(options:DefaultFirebaseOptions.currentPlatform);

  // ── Hive init ────────────────────────────────────────────────────────────
  await Hive.initFlutter();
  Hive.registerAdapter(ExpenseAdapter());
  Hive.registerAdapter(BudgetAdapter());

  await Hive.openBox('settings');
  await Hive.openBox<Expense>('expenses');
  await Hive.openBox<Budget>('budgets');

  await CurrencyService.init();

  runApp(const ProviderScope(child: MyApp()));
}

// ConsumerWidget so it can reactively follow the persisted ThemeMode
class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);

    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Show a loading indicator while the auth state is resolving
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            theme: AppTheme.darkTheme,
            home: const Scaffold(
              backgroundColor: Color(0xFF09090F),
              body: Center(
                child: CircularProgressIndicator(
                  valueColor:
                      AlwaysStoppedAnimation<Color>(Color(0xFF00BFA5)),
                ),
              ),
            ),
          );
        }

        // User is authenticated → run the full app with GoRouter
        if (snapshot.hasData && snapshot.data != null) {
          return MaterialApp.router(
            title: 'SmartWallet',
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeMode,
            routerConfig: goRouter,
            debugShowCheckedModeBanner: false,
          );
        }

        // User is not authenticated → show the login screen
        return MaterialApp(
          title: 'SmartWallet',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          debugShowCheckedModeBanner: false,
          home: const LoginScreen(),
        );
      },
    );
  }
}
